name: Download SBOM

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *' # Run every 5 min
jobs:
  download-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Set timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV


    - name: Use GitHub CLI command
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sbom="$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom)"

        echo "sbom:$sbom" >> sbom.json
        SPDXID=$(jq -r '.SPDXID' sbom.json)
        echo $SPDXID
        
        curl -L "https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.25.0/cyclonedx-linux-x64" -o cyclonedx-linux-x64
        chmod +x cyclonedx-linux-x64
        ./cyclonedx-linux-x64 --version
        ./cyclonedx-linux-x64 convert --input-file sbom.json --output-file cyclonedx.json
        cat cyclonedx.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-sbom-${{ env.TIMESTAMP }}
        path: |
          sbom.json
        if-no-files-found: error
      
