name: Download SBOM

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *' # Run every 5 min
jobs:
  download-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Authenticate with GitHub CLI
      run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

    - name: Create timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"


    - name: Use GitHub CLI command
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ORG_NAME=${{ github.repository_owner }}
        REPO_NAME=${{ github.event.repository.name }}
        sbom="$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository_owner }}/${{ github.event.repository.name }}/dependency-graph/sbom)"

        echo "sbom:$sbom" >> sbom.json

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact-sbom-${{ steps.timestamp.outputs.timestamp }}
        path: |
          sbom.json
        if-no-files-found: error
      
